config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   get 'home', action: :new, controller: 'devise'
  # end
  devise_for :users
  resources :specialities
  # get 'profile/:id', action: :show, controller: 'doctors'
  resources :doctors
  resources :patients
  resources :appointments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  has_one_attached :image
  has_many :doctors
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_speciality, only: %i[ show edit update destroy ]
  before_action :set_breadcrumbs

  # GET /specialities or /specialities.json
  def index
    @specialities = Speciality.all
    @speciality = Speciality.new
  end

  # GET /specialities/1 or /specialities/1.json
  def show
  end

  # GET /specialities/new
  def new
    @speciality = Speciality.new
    authorize @speciality
  end

  # GET /specialities/1/edit
  def edit
    authorize @speciality
  end

  # POST /specialities or /specialities.json
  def create
    flag = false
    @speciality = Speciality.find_by(id: speciality_params[:id])

    if @speciality.nil?
      @speciality = Speciality.new(speciality_params)
      authorize @speciality
      flag = true if @speciality.save
    else
      authorize @speciality, :update?
      flag = true if @speciality.update(speciality_params)
    end

    respond_to do |format|
      if flag
        format.html { redirect_to specialities_url, notice: "Speciality was successfully Saved." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialities/1 or /specialities/1.json
  def update
    authorize @speciality
    respond_to do |format|
      if @speciality.update(speciality_params)
        format.html { redirect_to speciality_url(@speciality), notice: "Speciality was successfully updated." }
        format.json { render :show, status: :ok, location: @speciality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1 or /specialities/1.json
  def destroy
    authorize @speciality
    @speciality.destroy

    respond_to do |format|
      format.html { redirect_to specialities_url, notice: "Speciality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_breadcrumbs
      add_breadcrumb("Specialities", specialities_path)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_speciality
      @speciality = Speciality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def speciality_params
      params.require(:speciality).permit(:name, :image, :id)
    end
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/_form.html.erb
<div class="modal fade " id="addSpeciality" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: speciality) do |form| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Speciality</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
            <div class="mb-3">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, class: "form-control" %>
              <%= form.hidden_field :id, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :image, class: "form-label" %>
              <%= form.file_field :image, class: "form-control" %>
            </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit  class: "btn btn-primary speciality-submit"%>
        </div>
      </div>
    <%end%>
  </div>
</div>

<script type="text/javascript">
  $(".edit-button").click(function() {
    $(".speciality-submit").val("Edit Speciality")
    name = $(this).attr("data-name")
    id   = $(this).attr("data-id")

    $("#speciality_name").val(name)
    $("#speciality_id").val(id)
  })
</script>

app/views/specialities/_speciality.html.erb
<div id="<%= dom_id speciality %>">
  <p>
    <strong>Name:</strong>
    <%= speciality.name %>
  </p>

</div>

app/views/specialities/edit.html.erb
<h1>Editing speciality</h1>

<%= render "form", speciality: @speciality %>

<br>

<div>
  <%= link_to "Show this speciality", @speciality %> |
  <%= link_to "Back to specialities", specialities_path %>
</div>

app/views/specialities/index.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-8 d-flex justify-content-start">
              <a href="#" data-bs-toggle="modal" data-bs-target="#addSpeciality" data-bs-whatever= <%="#{@specialities.count}"%> class="btn btn-dark"><i class="fa-solid fa-plus"></i> Add</a>
            </div>
            <div class="col-md-4 d-flex justify-content-end">
              <button type="button" class="btn btn-light list-view-btn">
                <i class="fa-solid fa-list" style ="color: black; height: 22px"></i>
              </button>
              <button type="button" class="btn btn-light grid-view-btn">
                <i class="fa-solid fa-border-all " style ="color: #black; height: 22px;"></i>
              </button>
            </div>
          </div>
        </div>

        <div class="card-body list-view">
          <table class="table table-borderless table-sm table-hover">
            <thead>
              <tr class="table-columns">
                <th scope="col">SID</th>
                <th scope="col" >Name</th>
                <th scope="col" >Doctors #</th>
                <th scope="col" >Created At</th>
                <th scope="col" >Updated At</th>
                <th scope="col" class="tab-end">EDIT | Delete</th>
              </tr>
            </thead>
            <tbody>
              <% @specialities.each do |speciality| %>
                <tr class = "table-rows">
                  <th scope="row">#<%= speciality.id%></th>
                  <td >
                    <div class="table-avatar">
                      <div class="spl-img">
                        <%= image_tag(speciality.image, style: 'width:100%') %>
                      </div>
                      <div class="" >
                        <%= speciality.name%>
                      </div>
                    </div>
                  </td>
                  <td >
                    <%= speciality.doctors.count %>
                  </td>
                  <td>
                    <%= parse_dates speciality.created_at %>
                  </td>
                  <td>
                    <%= parse_dates speciality.updated_at %>
                  </td>
                  <td class="tab-end">
                    <a class="text-black actions edit-button" href="#" data-bs-toggle="modal" data-bs-target="#addSpeciality" data-name = <%="#{speciality.name}"%> data-id= <%="#{speciality.id}"%>>
                      <i class="fa-solid fa-file-pen"></i> Edit
                    </a>
                    |
                    <a class="text-danger actions" data-turbo-method="delete" data-turbo-confirm="Are you sure?" href="<%= speciality_path(speciality)%>">
                      <i class="fa-solid fa-trash"></i> Delete
                    </a>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>

        <div class="card-body grid-view">
          <div class="row">
            <% @specialities.each do |speciality| %>

              <div class="col-md-3" style= "margin-bottom: 20px">
                <div class="card" style="width: fit-content;">
                  <div class="" style="text-align: center">
                    <%= image_tag(speciality.image, class: "card-image") %>

                  </div>
                  <hr style = "margin-top: 0px">
                  <div class="card-body">
                    <h5 class="card-title">Dr. <%= speciality.name%></h5>
                    <p class="text-muted mb-0"><i class="fa-solid fa-stethoscope"></i> <%=speciality.name%></p>
                    <p class="text-muted mb-0"><i class="fa-solid fa-hashtag"></i>  Doctors: <%=speciality.doctors.count%></p>
                  </div>
                </div>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(".grid-view").hide()
  $(".grid-view-btn").click(function() {
    $(".list-view").hide()
    $(".grid-view").show()
  })
  $(".list-view-btn").click(function() {
    $(".grid-view").hide()
    $(".list-view").show()
  })
</script>

<%= render "form", speciality: @speciality %>

app/views/specialities/new.html.erb
<h1>New speciality</h1>

<%= render "form", speciality: @speciality %>

<br>

<div>
  <%= link_to "Back to specialities", specialities_path %>
</div>

app/views/specialities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @speciality %>

<div>
  <%= link_to "Edit this speciality", edit_speciality_path(@speciality) %> |
  <%= link_to "Back to specialities", specialities_path %>

  <%= button_to "Destroy this speciality", @speciality, method: :delete %>
</div>