config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   get 'home', action: :new, controller: 'devise'
  # end
  devise_for :users
  resources :specialities
  # get 'profile/:id', action: :show, controller: 'doctors'
  resources :doctors
  resources :patients
  resources :appointments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(var(--bs-dark-rgb), var(--bs-bg-opacity)) !important;">
    © 2020 Copyright:
    <a class="text-white" href="#">Doc App</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container-fluid">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <i class="fa-solid fa-hospital hospital-icon "></i>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="<%= doctors_path %>" class="nav-link text-white">
                <i class="fa-solid fa-house bi d-block mx-auto mb-1 nav-icons"></i>
                Home
              </a>
            </li>
            <li>
              <a href="<%= specialities_path %>" class="nav-link text-white">
                <i class="fa-solid fa-briefcase-medical bi d-block mx-auto mb-1 nav-icons"></i>
                Specialities
              </a>
            </li>
            <li>
              <a href="<%= doctors_path %>" class="nav-link text-white">
                <i class="fa-solid fa-user-doctor bi d-block mx-auto mb-1 nav-icons"></i>
                Doctors
              </a>
            </li>
            <li>
              <a href="<%= patients_path %>" class="nav-link text-white">
                <i class="fa-solid fa-user bi d-block mx-auto mb-1 nav-icons"></i>
                Patients
              </a>
            </li>
            <li>
              <% if user_signed_in? %>
                <a href="<%= get_log_in_user[:show_profile]%>" class="nav-link text-white">
                  <i class="fa-solid fa-calendar-plus bi d-block mx-auto mb-1 nav-icons"></i>
                  Appointments
                </a>
              <%end%>
            </li>
            <li>
              <a href="#" class="nav-link text-white" >
                <i class="fa-solid fa-id-card bi d-block mx-auto mb-1 nav-icons"></i>
                Reports
              </a>
            </li>
            <%if !user_signed_in?%>
              <li style = "padding-top: 3px">
                <a href="<%= new_user_session_path %>" class="btn btn-light sign_in_btn" >
                  <i class="fa-solid fa-user bi d-block mx-auto mb-1 nav-icons"></i>
                  Log In
                </a>
              </li>
            <%end%>
          </ul>

          <%if user_signed_in?%>
            <%if current_user.role == 'admin'%>
              <div class="dropdown " style="margin-left:45px">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                  <img src="https://github.com/mdo.png" alt="mdo" width="38" height="38" class="rounded-circle">
                </a>
                <%name = current_user.first_name + " " + current_user.last_name%>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                  <li><a class="dropdown-item" href="#"><%= name %></a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="text-black actions" data-turbo-method="delete" href=" <%= destroy_user_session_path %>" >
                      <i class="fa-solid fa-file-pen"></i> Log Out
                    </a>
                  </li>
                </ul>
              </div>

            <%else%>
              <% logged_in_user = get_log_in_user %>
              <div class="dropdown " style="margin-left:45px">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= image_tag(logged_in_user[:user].image, class: "rounded-circle", width: "45", height: "38") %>
                </a>
                <%name = logged_in_user[:user].first_name + " " + logged_in_user[:user].last_name%>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                  <li><a class="dropdown-item" href="#"><%=name%></a></li>
                  <li><hr class="dropdown-divider"></li>

                  <li>
                    <a class="text-black actions dropdown-item"  href=" <%= logged_in_user[:show_profile] %>" >
                      <i class="fa-solid fa-eye"></i> Profile
                    </a>
                  </li>
                  <li><hr class="dropdown-divider"></li>

                  <li>
                    <a class="text-black actions dropdown-item"  href=" <%= logged_in_user[:edit_profile] %>" >
                      <i class="fa-solid fa-file-pen"></i> Edit Profile
                    </a>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="text-black actions dropdown-item" data-turbo-method="delete" href=" <%= destroy_user_session_path %>" >
                     <i class="fa-solid fa-user"></i> Log Out
                    </a>
                  </li>
                </ul>
              </div>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>


    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container-fluid ">
        <div class="row">

          <div class="col-md-6 d-flex justify-content-start">
            <div class="color-controls " style="margin-left: 20px">
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="<%= doctors_path%>">Home</a></li>
                  <% breadcrumbs.each do |crumb| %>
                    <%if breadcrumbs.last == crumb%>
                    <li class="breadcrumb-item active" aria-current="page">
                      <%= crumb.name %>
                    </li>
                    <%else%>
                      <li class="breadcrumb-item">
                        <%= link_to crumb.name, crumb.path, class: "breadcrumb-link" %>
                      </li>
                    <%end%>
                  <%end%>
                </ol>
              </nav>
            </div>
          </div>

          <div class="col-md-6 d-flex justify-content-end">
            <div class="view-controls" style="margin-right: 20px">
              <i class="fa-solid fa-sun fa-spin display-controls" style ="color: #ffdf00; height: 26px;"></i>
              <i class="fa-solid fa-star-and-crescent fa-spin display-controls" style ="height: 26px; margin-left: 7px;"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
</header>

app/views/shared/_side_bar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px; height: 680px">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>