config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   get 'home', action: :new, controller: 'devise'
  # end
  devise_for :users
  resources :specialities
  # get 'profile/:id', action: :show, controller: 'doctors'
  resources :doctors
  resources :patients
  resources :appointments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one_attached :image
  has_many :appointments
  has_many :doctors, through: :appountments

  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true

  after_create :create_users

  def create_users
    User.create(first_name: first_name, last_name: last_name, email: email, password: password, role: "patient")
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :set_breadcrumbs

  def index
    @patients = Patient.all
    authorize @patients
  end

  def new
    @patient = Patient.new
    authorize @patient
  end

  def create
    @patient = Patient.new(patient_params)
    authorize @patient
    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_url, notice: "Patient was successfully Created." }
      else
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    authorize @patient
    start_date = params.fetch(:start_date, Date.today).to_date
    @appointments = @patient.appointments.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def edit
    authorize @patient
  end

  def update
    authorize @patient
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_url, notice: "Patient was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @patient
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to specialities_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def set_breadcrumbs
      add_breadcrumb("Patients", patients_path)
      add_breadcrumb("Add Patient", new_patient_path) if action_name == "new"
      add_breadcrumb("Edit #{@patient.first_name}") if action_name == "edit"
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :password, :image, :phone, :address)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-md-4 patient-image">
      <img src="https://img.freepik.com/free-vector/doctor-character-background_1270-84.jpg?size=338&ext=jpg&ga=GA1.2.1491718101.1666749255" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" loading="lazy", style = "height: 100%; border-radius: 1%">
    </div>

    <div class="col-md-8 patient-form">
      <div class="patient-page-content patient-new ">
        <div class="card">
          <h5 class="card-header">Patients</h5>
          <div class="card-body">

            <%= form_with(model: @patient) do |form| %>
              <div class="row g-3">

                <div class="col-md-6">
                  <%= form.label :first_name, class: "form-label" %>
                  <%= form.text_field :first_name, class: "form-control #{'red-border' if get_errors(:first_name, @patient)[0]}"  %>
                  <% if get_errors(:first_name, @patient)[0] %>
                    <p class = "error_message">
                      <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:first_name, @patient)[1]%>
                    </p>
                  <%end%>
                </div>

                <div class="col-md-6">
                  <%= form.label :last_name, class: "form-label" %>
                  <%= form.text_field :last_name, class: "form-control #{'red-border' if get_errors(:last_name, @patient)[0]}" %>
                  <% if get_errors(:last_name, @patient)[0] %>
                    <p class = "error_message">
                      <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:last_name, @patient)[1]%>
                    </p>
                  <%end%>
                </div>

                <div class="col-md-6">
                  <%= form.label :email, class: "form-label #{'red-border' if get_errors(:email, @patient)[0]}" %>
                  <%= form.email_field :email, class: "form-control" %>
                  <% if get_errors(:email, @patient)[0] %>
                    <p class = "error_message">
                      <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:email, @patient)[1]%>
                    </p>
                  <%end%>
                </div>

                <div class="col-md-6">
                  <%= form.label :password, class: "form-label #{'red-border' if get_errors(:password, @patient)[0]}" %>
                  <%= form.email_field :password, class: "form-control" %>
                  <% if get_errors(:password, @patient)[0] %>
                    <p class = "error_message">
                      <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:password, @patient)[1]%>
                    </p>
                  <%end%>
                </div>

                <div class="col-md-6">
                  <%= form.label :image, class: "form-label" %>
                  <%= form.file_field :image, class: "form-control" %>
                </div>

                <div class="col-md-6">
                  <%= form.label :address, class: "form-label" %>
                  <%= form.text_field :address, class: "form-control" %>
                </div>

                <div class="col-md-6">
                  <%= form.label :phone, class: "form-label" %>
                  <%= form.text_field :phone, class: "form-control" %>
                </div>


                <div class="col-12 tab-end">
                  <button type="submit" class="btn btn-primary">Back</button>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>

            <%end%>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<%= render "form", patient: @patient %>

app/views/patients/index.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-8 d-flex justify-content-start">
              <a class="btn btn-dark" href="<%= new_patient_path %>" >
                <i class="fa-solid fa-plus"></i> Add
              </a>
            </div>

            <div class="col-md-4 d-flex justify-content-end">
              <button type="button" class="btn btn-light list-view-btn">
                <i class="fa-solid fa-list" style ="color: black; height: 22px"></i>
              </button>
              <button type="button" class="btn btn-light grid-view-btn">
                <i class="fa-solid fa-border-all " style ="color: #black; height: 22px;"></i>
              </button>
            </div>
          </div>
        </div>

        <div class="card-body list-view">
          <table class="table table-borderless table-sm table-hover">
            <thead>
              <tr class="table-columns">
                <th scope="col">SID</th>
                <th scope="col" >Patient</th>
                <th scope="col" >Email</th>
                <th scope="col" >Phone</th>
                <th scope="col" >Address</th>
                <th scope="col" class="tab-end">EDIT | DELETE</th>
              </tr>
            </thead>
            <tbody>
              <% @patients.each do |patient| %>
                <tr class = "table-rows">
                  <th scope="row">#<%= patient.id%></th>
                  <td >
                    <div class="table-avatar">
                      <div class="spl-img">
                        <%= image_tag(patient.image, style: 'width:100%') %>
                      </div>
                      <div >
                        <%name = patient.first_name + " " + patient.last_name%>
                        <%= name %>
                      </div>
                    </div>
                  </td>
                  <td>
                    <%= patient.email %>
                  </td>
                  <td>
                    <%= patient.phone %>
                  </td>
                  <td>
                    <%= patient.address %>
                  </td>
                  <td class="tab-end">
                    <a class="text-black actions" href=" <%= edit_patient_path(patient) %>" >
                      <i class="fa-solid fa-file-pen"></i> Edit
                    </a>
                    |
                    <a class="text-danger actions"  data-turbo-method="delete" data-turbo-confirm="Are you sure?" href="<%= patient_path(patient)%>" >
                      <i class="fa-solid fa-trash"></i> Delete
                    </a>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>

        <div class="card-body grid-view">
          <div class="row">
            <% @patients.each do |patient| %>

              <div class="col-md-3" style= "margin-bottom: 20px">
                <div class="card" style="width: fit-content;">
                  <div class="" style="text-align: center">
                    <%= image_tag(patient.image, class: "card-image") %>

                  </div>
                  <hr style = "margin-top: 0px">
                  <div class="card-body">
                    <%name = patient.first_name + " " + patient.last_name%>

                    <h5 class="card-title"><%= name%></h5>
                    <p class="text-muted mb-0"><i class="fa-solid fa-mobile-retro"></i> <%=patient.phone%></p>
                    <p class="text-muted mb-0"><i class="fa-solid fa-square-envelope"></i> <%=patient.email%></p>
                  </div>
                </div>
              </div>
            <%end%>
          </div>

        </div>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(".grid-view").hide()
  $(".grid-view-btn").click(function() {
    $(".list-view").hide()
    $(".grid-view").show()
  })
  $(".list-view-btn").click(function() {
    $(".grid-view").hide()
    $(".list-view").show()
  })
</script>

app/views/patients/new.html.erb
<%= render "form", patient: @patient %>

app/views/patients/show.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <%name = @patient.first_name + " " + @patient.last_name%>
            <div class="col-md-8 d-flex justify-content-start">
              <%= name%>
            </div>

            <div class="col-md-4 d-flex justify-content-end">
              Appointments
            </div>
          </div>
        </div>

        <div class="card-body ">
          <div class="row">
            <div class="col-md-4 doc-profile">
              <div class="card">
                <div class="" style="text-align: center;   background-color: whitesmoke;">
                  <%= image_tag(@patient.image, class: "show-page-card-image") %>

                </div>
                <hr style = "margin-top: 0px">
                <div class="card-body">
                  <h5 class="card-title"><%= name%></h5>
                  <p class="text-muted mb-0"><i class="fa-solid fa-mobile-retro"></i> <%=@patient.phone%></p>
                  <p class="text-muted mb-0"><i class="fa-solid fa-square-envelope"></i> <%=@patient.email%></p>
                </div>
              </div>
            </div>

            <div class="col-md-8 doc-availability">
              <div class="card booking-schedule schedule-widget">
                <div class="schedule-header">
                  <div class="row">
                    <div class="col-md-12">
                      <%= week_calendar(number_of_weeks: 4, events: @appointments) do |date, appointments| %>
                        <div class="day">
                          <%= date %>
                        </div>
                        <% appointments.each do |appointment|%>
                          <div class="card-header">
                            <div class="card-title">
                              <%= appointment.title%>
                            </div>
                          </div>
                        <%end%>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>