config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   get 'home', action: :new, controller: 'devise'
  # end
  devise_for :users
  resources :specialities
  # get 'profile/:id', action: :show, controller: 'doctors'
  resources :doctors
  resources :patients
  resources :appointments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_one_attached :image
  belongs_to :speciality
  has_many :appointments

  has_many :patients, through: :appountments

  # scope :owner, -> { where(first_name: "Gurjot1") }

  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true

  after_create :create_users

  def create_users
    User.create(first_name: first_name, last_name: last_name, email: email, password: password, role: "doctor")
  end


  def self.owner
      where(first_name: "Gurjot1")
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_doctor, only: %i[ show edit update destroy ]
  before_action :set_breadcrumbs


  def index
    @doctors = Doctor.all
  end

  def new
    @specialities = Speciality.all
    @doctor = Doctor.new
    authorize @doctor
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @specialities = Speciality.all
    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctors_url, notice: "Doctor was successfully Created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    @appointment = Appointment.new
    start_date = params.fetch(:start_date, Date.today).to_date
    @appointments = @doctor.appointments.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def edit
    authorize @doctor
    @specialities = Speciality.all
  end

  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctors_url, notice: "Doctor was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @doctor
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to specialities_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def set_breadcrumbs
      add_breadcrumb("Doctors", doctors_path)
      add_breadcrumb("Add Doctor", new_doctor_path) if action_name == "new"
      add_breadcrumb("Edit #{@doctor.first_name}") if action_name == "edit"

    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :email, :password, :speciality_id, :image, :status)
    end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-md-4 patient-image">
      <img src="https://img.freepik.com/free-vector/doctor-concept-illustration_114360-1072.jpg?size=338&ext=jpg&ga=GA1.2.1491718101.1666749255" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="370" loading="lazy", style = "height: 393px; border-radius: 1%">
    </div>

    <div class="col-md-8">
      <div class="card">
        <h5 class="card-header">Doctors</h5>
        <div class="card-body">

          <%= form_with(model: @doctor) do |form| %>
            <div class="row g-3">

              <div class="col-md-6">
                <%= form.label :first_name, class: "form-label" %>
                <%= form.text_field :first_name, class: "form-control #{'red-border' if get_errors(:first_name, @doctor)[0]}" %>
                <% if get_errors(:first_name, @doctor)[0] %>
                  <p class = "error_message">
                    <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:first_name, @doctor)[1]%>
                  </p>
                <%end%>
              </div>
              <div class="col-md-6">
                <%= form.label :last_name, class: "form-label" %>
                <%= form.text_field :last_name, class: "form-control #{'red-border' if get_errors(:last_name, @doctor)[0]} " %>
                <% if get_errors(:last_name, @doctor)[0] %>
                  <p class = "error_message">
                    <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:last_name, @doctor)[1]%>
                  </p>
                <%end%>
              </div>

              <div class="col-md-6">
                <%= form.label :speciality_id, class: "form-label" %>
                <div class="form-select">
                  <%= form.select :speciality_id, @specialities.map{|s| [s.name, s.id]}, id: "doctor_speciality_id"  %>
                </div>
              </div>

              <div class="col-md-6">
                <%= form.label :image, class: "form-label" %>
                <%= form.file_field :image, class: "form-control" %>
              </div>

              <div class="col-md-6">
                <%= form.label :email, class: "form-label" %>
                <%= form.email_field :email, class: "form-control #{'red-border' if get_errors(:email, @doctor)[0]}" %>
                <% if get_errors(:email, @doctor)[0] %>
                  <p class = "error_message">
                    <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:email, @doctor)[1]%>
                  </p>
                <%end%>
              </div>
              <div class="col-md-6">
                <%= form.label :password, class: "form-label" %>
                <%= form.text_field :password, class: "form-control #{'red-border' if get_errors(:password, @doctor)[0]}" %>
                <% if get_errors(:password, @doctor)[0] %>
                  <p class = "error_message">
                    <i class="fa-solid fa-triangle-exclamation error_icon"></i><%=get_errors(:password, @doctor)[1]%>
                  </p>
                <%end%>
              </div>

              <div class="col-12 tab-end">
                <button type="submit" class="btn btn-primary">Back</button>
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>

          <%end%>

        </div>
      </div>
    </div>
  </div>


</div>

app/views/doctors/edit.html.erb
<%= render "form", speciality: @speciality %>

app/views/doctors/index.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-8 d-flex justify-content-start">

              <a class="btn btn-dark" href="<%= new_doctor_path %>" >
                <i class="fa-solid fa-plus"></i> Add
              </a>
            </div>

            <div class="col-md-4 d-flex justify-content-end">
              <button type="button" class="btn btn-light list-view-btn">
                <i class="fa-solid fa-list" style ="color: black; height: 22px"></i>
              </button>
              <button type="button" class="btn btn-light grid-view-btn">
                <i class="fa-solid fa-border-all " style ="color: #black; height: 22px;"></i>
              </button>
            </div>
          </div>
        </div>
        <!-- <hr> -->
        <div class="card-body list-view">
          <table class="table table-borderless table-sm table-hover">
            <thead>
              <tr class="table-columns">
                <th scope="col">SID</th>
                <th scope="col" >Doctor</th>
                <th scope="col" >Email</th>
                <th scope="col" >Speciality</th>
                <th scope="col" >Created At</th>
                <th scope="col" >Updated At</th>
                <th scope="col" class="tab-end">EDIT | Delete</th>
              </tr>
            </thead>
            <tbody>
              <% @doctors.each do |doctor| %>
                <tr class = "table-rows">
                  <th scope="row">#<%= doctor.id%></th>
                  <td >
                    <div class="table-avatar">
                      <div class="spl-img">
                        <%= image_tag(doctor.image, style: 'width:100%') %>
                      </div>
                      <div >
                        <%name = doctor.first_name + " " + doctor.last_name%>
                        <%= name %>
                      </div>
                    </div>
                  </td>
                  <td>
                    <%= doctor.email %>
                  </td>
                  <td>
                    <%= doctor.speciality.name %>
                  </td>
                  <td>
                    <%= parse_dates(doctor.created_at) %>
                  </td>
                  <td>
                    <%= parse_dates(doctor.updated_at) %>
                  </td>
                  <td class="tab-end">
                    <a class="text-black actions" href=" <%= edit_doctor_path(doctor) %>" >
                      <i class="fa-solid fa-file-pen"></i> Edit
                    </a>
                    |
                    <a class="text-danger actions"  data-turbo-method="delete" data-turbo-confirm="Are you sure?" href="<%= doctor_path(doctor)%>" >
                      <i class="fa-solid fa-trash"></i> Delete
                    </a>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="card-body grid-view">
          <div class="row">
            <% @doctors.each do |doctor| %>

              <div class="col-md-3" style= "margin-bottom: 20px">
                <div class="card" style="width: fit-content;">
                  <div class="" style="text-align: center">
                    <%= image_tag(doctor.image, class: "card-image") %>

                  </div>
                  <hr style = "margin-top: 0px">
                  <div class="card-body">
                    <%name = doctor.first_name + " " + doctor.last_name%>

                    <h5 class="card-title">Dr. <%= name%></h5>
                    <p class="text-muted mb-0"><i class="fa-solid fa-stethoscope"></i> <%=doctor.speciality.name%></p>
                    <p class="text-muted mb-0"><i class="fa-solid fa-square-envelope"></i> <%=doctor.email%></p>
                  </div>
                </div>
              </div>
            <%end%>
          </div>



        </div>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">
  $(".grid-view").hide()
  $(".grid-view-btn").click(function() {
    $(".list-view").hide()
    $(".grid-view").show()
  })
  $(".list-view-btn").click(function() {
    $(".grid-view").hide()
    $(".list-view").show()
  })
</script>

app/views/doctors/new.html.erb
<%= render "form", speciality: @speciality %>

app/views/doctors/show.html.erb
<div class="page-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-8 d-flex justify-content-start">
              <%if current_user.doctor?%>
              <%else%>
                <a href="#" data-bs-toggle="modal" data-bs-target="#addAppointment" class="btn btn-dark"><i class="fa-solid fa-plus"></i> Appointment
                </a>
              <%end%>
            </div>

            <div class="col-md-4 d-flex justify-content-end">
              Availability
            </div>
          </div>
        </div>

        <div class="card-body ">
          <div class="row">
            <div class="col-md-4 doc-profile">
              <div class="card">
                <div class="" style="text-align: center;   background-color: whitesmoke;">
                  <%= image_tag(@doctor.image, class: "show-page-card-image") %>

                </div>
                <hr style = "margin-top: 0px">
                <div class="card-body">
                  <%name = @doctor.first_name + " " + @doctor.last_name%>

                  <h5 class="card-title">Dr. <%= name%></h5>
                  <p class="text-muted mb-0"><i class="fa-solid fa-stethoscope"></i> <%=@doctor.speciality.name%></p>
                  <p class="text-muted mb-0"><i class="fa-solid fa-square-envelope"></i> <%=@doctor.email%></p>
                </div>
              </div>
            </div>

            <div class="col-md-8 doc-availability">
              <div class="card booking-schedule schedule-widget">
                <div class="schedule-header">
                  <div class="row">
                    <div class="col-md-12">
                      <%= week_calendar(number_of_weeks: 4, events: @appointments) do |date, appointments| %>
                        <div class="day">
                          <%= date %>
                        </div>
                        <% appointments.each do |appointment|%>
                          <div class="card-header">
                            <div class="card-title">
                              <%= appointment.title%>
                            </div>
                          </div>
                        <%end%>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>





<div class="modal fade " id="addAppointment" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: @appointment) do |form| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Speciality</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
          <div class="row g-3">

            <div class="col-md-6">
              <%= form.label :title, class: "form-label" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="col-md-6">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_field :description, class: "form-control" %>
              <%= form.hidden_field :doctor_id, value: @doctor.id %>
            </div>

            <div class="col-md-6">
              <%= form.label :start_date, class: "form-label" %>
              <%= form.datetime_field :start_time, class: "form-control" %>
            </div>

          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit  class: "btn btn-primary speciality-submit"%>
        </div>
      </div>
    <%end%>
  </div>
</div>